site_name: Card Game App
site_url: https://Kanaichi333.github.io/streamlit-practice/
theme:
  name: material
nav:
  - Home: index.md
  - High and Low: how_to_use/high_and_low.md
repo_url: https://github.com/Kanaichi333/streamlit-practice
extra:
  version:
    provider: mike
